### ISSUE TITLE
Спроектировать REST API в swagger.

### ISSUE THREAD

**Issue by PaladinSasha** [Zhilg/BMSTU_TeamDev#1]
Использовать все возможные подходящие методы. Рассматривай случаи когда возвращается список, список не должен возвращать все записи, а должен возвращать постранично. 
Смотри ТЗ (https://github.com/Zhilg/BMSTU_TeamDev/wiki/%D0%A2%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5#%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D0%B0)

**Comment by Andebugan** [comment]
В issue - решение проблем, для постановки задач используются тикеты
