### ISSUE TITLE
PostgreSQL БД - реализация файлов для docker и инициализации

### ISSUE THREAD

**Issue by Andebugan** [Zhilg/BMSTU_TeamDev#2]
## Описание задачи
- [x] Написать SQL файл для инциализации в базе таблиц, содержащих данные для сущностей проекта
- [x] Написать Dockerfile для подъема контейнера с базой

## Заметки по тестированию
Необходимо проверять корректность инициализации БД

## Ссылки
- [техническое задание](https://github.com/Zhilg/BMSTU_TeamDev/wiki/%D0%A2%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5#%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D0%B8-%D0%B1%D0%B0%D0%B7%D1%8B-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85)

**Comment by ak-karimzai** [comment]
**Сделание задачи**
- в папке `schema` написал два скрипта, первый инициализирует схему БД и второй деинициализирует cхему БД.
- написал файл `docker-compose.yml` который поднемает контенер postgresql.
- также написан `makefile` с скриптами поднятие контенера, инициализации и деинициализации БД.

все проверил у себя локально работает.
