### ISSUE TITLE
Написание openapi описания реализуемого API в формате yaml

### ISSUE THREAD

**Issue by Andebugan** [Zhilg/BMSTU_TeamDev#7]
## Описание задачи
Необходимо описать реализуемое публичное API сервиса в формате openapi в yaml файле. Полученный файл со спецификацией положить в папку api в корне проекта. Если её нет - создать.

**Comment by ak-karimzai** [comment]
**Сделан**
в папке `api` находиться реализации OpenApi документации проекта.

**Comment by Zhilg** [comment]
Документация добавлена, закрываю issue
